### ISSUE TITLE
Error thrown when building for Java with Maven

### ISSUE THREAD

**Issue by adeamoo-gel** [genomicsengland/GelReportModels#533]
Hi @Antonior26 ,

Apologies in advance if you're not the right contact for this issue but I saw that you were the one that created this latest release. I'm running into the issue below when trying to use the Gel Models in my code.

When running the command 'mvn install' the build fails with the following error:

`Traceback (most recent call last):
  File "C:\Users\aadegunamoo\Documents\Workspace\testing\automation\GelReportModels\build.py", line 11, in <module>
    import protocols_utils.utils.conversion_tools as conversion_tools
  File "C:\Users\aadegunamoo\Documents\Workspace\testing\automation\GelReportModels\protocols_utils\utils\conversion_tools.py", line 11, in <module>
    from protocols_utils.code_generation.process_schemas import SchemaGenerator, ProtocolGenerator
  File "C:\Users\aadegunamoo\Documents\Workspace\testing\automation\GelReportModels\protocols_utils\code_generation\process_schemas.py", line 19, in <module>
    import avro.schema
ModuleNotFoundError: No module named 'avro'`

This issue causes the framework I'm working to fail when importing the gel-models as a maven dependency or when trying to package locally.

[GelReportModel7.8.0.log](https://github.com/genomicsengland/GelReportModels/files/7251457/GelReportModel7.8.0.log)

**Comment by lucventurini** [comment]
Dear @adeamoo-gel ,

Would installing avro (e.g. `pip install avro`) solve the issue?

**Comment by adeamoo-gel** [comment]
Hi @lucventurini,

Thanks for getting back to me. 

Is it something that can be imported as a java maven dependency? It looks like a missing python module and I'm not sure how it can be installed from a java environment (although i can look into it). The only dependency I found is :
`<groupId>org.apache.avro</groupId>
 <artifactId>avro</artifactId>
`
But I'm not sure whether it's the same as the python module.

**Comment by lucventurini** [comment]
Hi @adeamoo-gel ,

No, this is indeed a python dependency. @javild , would you know how to solve this?

**Comment by javild** [comment]
not really, @lucventurini Never built GRM myself. @andyb3 @kevinpetersavage any clue?

**Comment by adeamoo-gel** [comment]
Hi @andyb3, @kevinpetersavage,

Checking whether there is an update on this issue as it is blocking some of my work.

Thank you.

Regards,
@adeamoo-gel

**Comment by andyb3** [comment]
@adeamoo-gel I have only every build GRM for Python, but will see if I can find out more info
